package com.rc.productInventory.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

//import org.hibernate.annotations.CreationTimestamp;

@Entity
public class Product {
	@Column
	// allows the date to be generated by the system

	// sets the 'id' as the primary key
	@Id
	// allows the id to be generated by the underlying database

	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	private String productName;
	private String mfrName;
	private String productType;
	private String sku;

	public Product() {
	}
	// non-argument constructor needed for JPA

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getMfrName() {
		return mfrName;
	}

	public void setMfrName(String mfrName) {
		this.mfrName = mfrName;
	}

	public String getProductType() {
		return productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getSku() {
		return sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public Long getId() {
		return id;
	}

	public Product(String productName, String mfrName, String productType, String sku) {

		this.productName = productName;
		this.mfrName = mfrName;
		this.productType = productType;
		this.sku = sku;
	}

	@Override
	public String toString() {
		return "Product [id=" + id + ", productName=" + productName + ", mfrName=" + mfrName + ", productType="
				+ productType + ", sku=" + sku + "]";
	}

}
